import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter, Roboto } from 'next/font/google'

const inter = Inter({ 
  weight: ["300", "500", "700"],
  subsets: ['latin'] 
})

const roboto = Roboto({
  weight: ["300", "500", "700"],
  style: ['normal', 'italic'],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Moviez',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-slate-900 text-slate-100`}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
